### ISSUE TITLE
how to enable swipetyping?

### ISSUE THREAD

**Issue by maitra** [dslul/openboard#151]
Is it possible to enable swipetyping with this keyboard?

**Comment by ChildishGiant** [comment]
So far there is no swipe typing option as there are no foss libs to handle this (iirc)

**Comment by AlanSanchezP** [comment]
There's no way to enable it in currently distributed apks, the reason is what childishGiant said. 
It MIGHT get included in the future if anysoftkeyboard people fix their swipe implementation and then someone takes the involved pieces of code into open board. But that will take a long time, assuming it happens at all.

If you are techie enough you can read the discussion in #3 about how to include Google's lib for swipetyping.

**Comment by dslul** [comment]
Swype prediction needs to be implemented "only" in the backend part (in C++). [Here](https://github.com/dslul/openboard/tree/master/app/src/main/jni/src/suggest/policyimpl/typing) you can find the current typing implementation and [here](https://github.com/dslul/openboard/tree/master/app/src/main/jni/src/suggest/policyimpl/gesture) the stub for gesture typing.
