### ISSUE TITLE
Missing Emojis

### ISSUE THREAD

**Issue by rohit15079** [dslul/openboard#157]
Some emojis are missing from emoji's menu. Eg: 🥺 🥵 🥶

**Comment by Mhowser** [comment]
Same here, using latest release on Android 7 Nougat
![Screenshot_20201002-104710](https://user-images.githubusercontent.com/24195572/94953602-aedc1400-049c-11eb-91ed-88279165792e.png)

**Comment by MajeurAndroid** [comment]
This is due to [changes](https://github.com/LineageOS/android_packages_inputmethods_LatinIME/commit/0db9fe050f6c186fcf16e90554ecc1642033d464) that had been made in lineage 18.0. 
In lineageos, the keyboard app is bundled with the system so there is no reason for it to run on earlier Android versions than the system it's bundled with. All new emojis can thus be added to the common "all android versions" file "without" any risk...
But as we are a standalone app here, these changes should be placed only in corresponding values-vXX to be available only on versions that support them !
I am currently working on this.
