### ISSUE TITLE
[Feature Request] Keyboard following system theme

### ISSUE THREAD

**Issue by dbneo** [dslul/openboard#178]
If you open the keyboard at night you will get greeted by bright white keys. I think the app should follow system night/day mode.

**Comment by dslul** [comment]
Can you provide some screenshots?

**Comment by Glitchy-Tozier** [comment]
> Can you provide some screenshots?

Screenshots of what specifically? I think what he is suggesting is: Many devices have some kind of "night mode", where menus turn black instead of white to make the screen less bright. All he is suggesting is for the Keyboard to also switch it colors. (for example, switching from "material light border" to "material dark border".

Not sure what screenshots he should post in that case.

**Comment by dslul** [comment]
Oh you're right, I first thought there was some kind of bug...if I remember well there should be already an open issue about this, but I can't find it
