### ISSUE TITLE
German layout is wrong / has been changed

### ISSUE THREAD

**Issue by UserX404** [dslul/openboard#211]
Since 1.4.2 the default/first option behind 's' has been changed. 
It was 'ß' which is a often used character for me. Whereas the '#' is rarely used. Why has this layout been changed? Is there a option to switch to an other layout?
Cross-checked with Gboard
and 'ß' is the first option behind 's' (as desired).

Thank you.

Edit:
![Screenshot_20201108-200502](https://user-images.githubusercontent.com/14954521/98481943-4d773580-21fe-11eb-86d7-de5498606066.jpg)
German/Deutsch (Austria) is not available.

**Comment by kojid0** [comment]
Because key hints @ (a) and # (s) were added

**Comment by UserX404** [comment]
The hints are correct but behind 's' a sharp-s (ß) is expected.
I not sure if it's a difference between German (Austria) and normal German (Germany) but it was correct handled before and now it's wrong. Gboard, for refenece only, has the expected layoot with # hint but default ß.

![Screenshot_20201108-201734](https://user-images.githubusercontent.com/14954521/98482282-a9db5480-2200-11eb-8ccd-18d691bc87ab.png)
![Screenshot_20201108-201710](https://user-images.githubusercontent.com/14954521/98482286-aea00880-2200-11eb-8591-ecdc4bf61ae3.png)

**Comment by Glitchy-Tozier** [comment]
Ewww, that's disgusting! I wish I read about this before updating, now I can't downgrade anymore...

Please fix this, ß is really important for German, while # definitely isn't.
You can keep the indicator the same, but please don't replace the useful popups with useless stuff. Nobody will complain about having access to the letters they NEED.

> Because key hints @ (a) and # (s) were added

**a** is handled correctly: **ä** still is the primary popup. Please fix **s** to correctly display **ß** first.



@UserX404 Regarding German German & Austrian German:
I'm not 100% sure what your question is. 
- If it is "_Do those languages need the same letters?_", then yes, we write exactly the same. (Although we might have some minor tweaks regarding spelling)
- If your question is "_Does the Geman (Austria) Keyboard have the same issue?_", then i must say i don't know (because I don't know which layout I'm using, it just says "German"), but I assume they changed it for all of German. Which sucks.

**Comment by kojid0** [comment]
Will fix soon

**Comment by kojid0** [comment]
made a PR, dslul has to test and merge

**Comment by l3u** [comment]
I just wanted to report this exactly after the last F-Droid update. Nice that there's already a PR to fix it :-)

**Comment by HyknuF** [comment]
Oh I am happy, that this will be fixed soon, cause its hard to write on german layout this way ;-)

great keyboard though! I am loving the "swipe to delete" so much ;-)

**Comment by Offerel** [comment]
At least for me s has longpress ß available, but I miss @ on longpress of a in german language. If I switch to english, it's available.

**Comment by reinob** [comment]
The bug is with German language. If you long-press "s" you get the pop-up with "#" preselected, instead of the more common and expected "ß".

The first post already mentions version 1.4.2, which is the latest.

**Comment by dslul** [comment]
New release with the fix has been published, sorry for the delay.
