### ISSUE TITLE
Add an favorite tab for emojis.

### ISSUE THREAD

**Issue by Pranab009** [dslul/openboard#216]
Add an favorite tab for emoji's. because too much emoji's are available and we use some particular emoji's.
And recent tab is not enough.
Recent tab can stores little bit of emoji's.

**Comment by Glitchy-Tozier** [comment]
Emojis need to be improved in general. Lumping all the different skin-tones together (as we can see in Whatsapp for example) would GREATLY improve the Emoji-keyboard.
Currently, it feels kind of unusable.

**Comment by boomerAndy** [comment]
I second this. Either a search function or cluster the skin tones together like on Gboard is really needed because scrolling for nearly a full minute to find a single emoji really kills the flow of the UX. 
Amazing keyboard for an open project, but this is holding it back and switching to Gboard to find an emoji is quicker, which is a big red flag.
