### ISSUE TITLE
No learning of typed words

### ISSUE THREAD

**Issue by stefrey** [dslul/openboard#233]
I use the system language German (Swiss). I often write in Swiss German, for which no dictionaries exist. Hence, I'd be glad if OpenBoard would learn from what I type. Even though activated in the settings, the board seems to remember no word at all (settings: Force Inkognito mode = false, Personalized Prediction = true). Can anyone help?

**Comment by Offerel** [comment]
Is there any way to make this work? Maybe a workaround?

**Comment by dagli** [comment]
If there will be no learning, please remove "Personalized suggestions" option. It is misleading. I switched to this keyboard for learning feature.

**Comment by Offerel** [comment]
Sorry, but i cant confirm that. After your comment, i disabled the mentioned option and tried again to learn words, but no luck. It doesn't learn words. Maybe i have setup something the wrong way but at least with selected languages for English (US) and German it didn't work.

**Comment by ste-foo** [comment]
I tried removing "Personalized suggestion" too, typed 10 times Hallo Welt (engl. for hello world), but even after typing it 10 times, there is no suggestion at all after typing Hallo, the sugesstion bar remains empty. I'd be extremely happy if the keyboard would support learning of typed words. I know, I could switch to SwiftKey, but I prefer a half-working open source solution to a fully working data crawler monster. However, since auto completion would save me hours a day, I'd be glad to have this feature working...

**Comment by Offerel** [comment]
After installing apk version 1.4.3 from GitHub, this seems to be fixed. At least in my case it learns words like jabberwooky or similar, which are not in the dictionary.

**Comment by stefrey** [comment]
> After installing apk version 1.4.3 from GitHub, this seems to be fixed. At least in my case it learns words like jabberwooky or similar, which are not in the dictionary.

Works now, this is fantastic, thank you!!!

**Comment by stefrey** [comment]
:)
