### ISSUE TITLE
Language switch long press delay excessive

### ISSUE THREAD

**Issue by Immortalin** [dslul/openboard#27]
Long pressing the space button to trigger language/keyboard switch menu takes a fair bit longer than default gboard.

**Comment by dslul** [comment]
I was actually thinking about removing this one, since it's already possible to use the dedicated button on the keyboard or on the android navbar. I would like to hear more opinions though.

**Comment by jwsp1** [comment]
I'd rather change the dedicated language-button with Emoji-button (currently long-press enter), if you really want to keep the language-button. But the space bar already shows which language is currently selected, so it actually makes sense to change language by long-pressing it. 

Also, I could imagine to disable the dedicated language-button and keep long-press space button action to switch languages because as #7 might be implemented, it would remove necessity to have a dedicated button to change languages.

**Comment by dslul** [comment]
It turns out this long delay was actually a bug. Fixed now. Also, I finally added a toggle to switch off the globe key.

**Comment by dslul** [comment]
I'll close this since it's fixed in v1.3, if you still encounter this bug tell me and I'll reopen the issue.
