### ISSUE TITLE
Disable autocorrect when typing in email fields

### ISSUE THREAD

**Issue by pudup** [dslul/openboard#312]
Auto correct is not useful when typing in emails in email fields and should be disabled be default or at least with an option.

Currently typing the period ->(.) at the end of abc@somemail will auto correct the entire thing to alice bob charlie some mail. 

Openboard already detects email fields as evidenced by the fact that the @ symbol becomes available on the default keyboard.

**Comment by SimonCDalzell** [comment]
Better yet, disable autocorrect entirely if the user types an @ anywhere as part of a string without a space.

**Comment by bongochong** [comment]
This happens with the URL bar in most browsers as well. I recently reverted back to stock AOSP because OpenBoard's autocorrect is overzealously applied, and it became a hindrance. It is also inconsistent regarding apostrophes and has trouble with hyphenated terms. A real shame, because it's a much needed alternative and the most reliable of all the FOSS keyboards on Android.

**Comment by dslul** [comment]
Fixed https://github.com/dslul/openboard/pull/384
@bongochong are those issues all regressions?

**Comment by bongochong** [comment]
Sorry I missed this, but no, not regressions. Clearly you fixed them!
