### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by h1tech** [dslul/openboard#375]
Does OpenBoard have any type of privacy policy, and, if so, where can a user read it?

**Comment by NoahAndrews** [comment]
Seeing as the app doesn't even have network permissions, it's safe to say that it's not sending data off of your device. Not that there's no value in a privacy policy that says that explicitly.

**Comment by dslul** [comment]
Actually it does, since it's mandatory on the play store. It's this one https://gist.github.com/dslul/9518b6bbff3bdf802cc9a03012012924

I generated one using an online tool, as you can see from the history, but then I changed it to a one liner (I don't remember why). Of course, I don't know if it's adequate.

**Comment by h1tech** [comment]
> 
> 
> Actually it does, since it's mandatory on the play store. It's this one https://gist.github.com/dslul/9518b6bbff3bdf802cc9a03012012924
> 
> I generated one using an online tool, as you can see from the history, but then I changed it to a one liner (I don't remember why). Of course, I don't know if it's adequate.

Oh, thanks. What a nice and short privacy policy. Appreciate it so much!
