### ISSUE TITLE
Has the project being discontinued?

### ISSUE THREAD

**Issue by blogmangit** [dslul/openboard#457]
Hi there, since there is a gap of 6 months from the last update, I am just curious that has the project being discontinued or is still running. If so what's the eta for next update ?

**Comment by justaguydoinghisstuff** [comment]
I totally understand get that and i dont want to put any pressure. 
Then can someone help me getting an apk with issue #75 solved? dslul closed it bc it seems that he fixed it, but i have no idea on how to build from source, and especially not how to build from the correct pull request. 
Otherwise ill keep on waiting patiently.

**Comment by jnnkB** [comment]
See https://github.com/dslul/openboard/issues/454 for APKs generated by users

**Comment by Pentaphon** [comment]
> I totally understand get that and i dont want to put any pressure.

That being said, the issues are mounting at a rapid pace and Openboard is becoming very popular for an open source keyboard so @dslul may want to share the work with a maintainer with more time to devote to the project.

**Comment by dslul** [comment]
New version released
